"""Object Entry requirements."""
from __future__ import annotations

from app.services.procedure_requirements import (
    ProcedureRequirements,
    ProcedureRequirement,
    ProcedureRequirementGroup,
    _register,
)
from app.services.workflow_definitions import WORKFLOW_DEFINITIONS

_status_order = WORKFLOW_DEFINITIONS["object_entry"].status_order

OBJECT_ENTRY_REQUIREMENTS = _register(
    ProcedureRequirements(
        procedure_type="object_entry",
        procedure_label="Object Entry",
        procedure="Object Entry",
        status_order=_status_order,
        requirement_groups=[
            ProcedureRequirementGroup(
                id="entry",
                label="Entry Information",
                section_id="entry",
                requirements=[
                    ProcedureRequirement(
                        id="entry_number",
                        label="Entry number",
                        group_id="entry",
                        field_paths=["entry_number"],
                        required_for_statuses=["received", "processed", "returned", "acquired"],
                        severity="blocking",
                        help_text="A unique identifier assigned when objects are received.",
                    ),
                    ProcedureRequirement(
                        id="entry_date",
                        label="Entry date",
                        group_id="entry",
                        field_paths=["entry_date"],
                        required_for_statuses=["received", "processed", "returned", "acquired"],
                        severity="blocking",
                        help_text="The date objects arrived or are expected to arrive.",
                    ),
                    ProcedureRequirement(
                        id="reason",
                        label="Reason for entry",
                        group_id="entry",
                        field_paths=["entry_reason"],
                        required_for_statuses=["received", "processed"],
                        severity="blocking",
                        help_text="Why these objects are entering your care.",
                    ),
                    ProcedureRequirement(
                        id="receipt_reference",
                        label="Receipt reference",
                        group_id="entry",
                        field_paths=["receipt_reference"],
                        required_for_statuses=["processed"],
                        severity="recommended",
                        help_text="Reference number for the receipt given to the depositor.",
                    ),
                    ProcedureRequirement(
                        id="entry_method",
                        label="Entry method",
                        group_id="entry",
                        field_paths=["entry_method"],
                        required_for_statuses=["received", "processed"],
                        severity="recommended",
                        help_text="How the deposit arrived (hand delivery, post, courier, etc.).",
                    ),
                ],
            ),
            ProcedureRequirementGroup(
                id="authorization",
                label="Authorization",
                section_id="authorization",
                requirements=[
                    ProcedureRequirement(
                        id="authorizer_id",
                        label="Authorizer",
                        group_id="authorization",
                        field_paths=["authorizer_id"],
                        required_for_statuses=["processed"],
                        severity="blocking",
                        help_text="The person in your institution authorizing acceptance of this deposit (Procedure: Entry authorizer).",
                    ),
                    ProcedureRequirement(
                        id="authorization_date",
                        label="Authorization date",
                        group_id="authorization",
                        field_paths=["authorization_date"],
                        required_for_statuses=["processed"],
                        severity="recommended",
                        help_text="When the deposit was authorized.",
                    ),
                    ProcedureRequirement(
                        id="authorization_note",
                        label="Authorization note",
                        group_id="authorization",
                        field_paths=["authorization_note"],
                        required_for_statuses=[],
                        severity="info",
                        help_text="Notes about the authorization.",
                    ),
                ],
            ),
            ProcedureRequirementGroup(
                id="depositor",
                label="Depositor Information",
                section_id="depositor",
                requirements=[
                    ProcedureRequirement(
                        id="depositor_id",
                        label="Depositor",
                        group_id="depositor",
                        field_paths=["depositor_id"],
                        required_for_statuses=["received", "processed", "returned"],
                        severity="blocking",
                        help_text="The person or organization bringing objects to you.",
                    ),
                    ProcedureRequirement(
                        id="current_owner_id",
                        label="Current owner",
                        group_id="depositor",
                        field_paths=["current_owner_id"],
                        required_for_statuses=[],
                        severity="recommended",
                        help_text="The legal owner of the objects, if different from depositor.",
                    ),
                ],
            ),
            ProcedureRequirementGroup(
                id="objects",
                label="Objects Description",
                section_id="objects",
                requirements=[
                    ProcedureRequirement(
                        id="objects_description",
                        label="Brief description",
                        group_id="objects",
                        field_paths=["objects_description"],
                        required_for_statuses=["received", "processed", "returned"],
                        severity="blocking",
                        help_text="A description sufficient to identify the objects.",
                    ),
                    ProcedureRequirement(
                        id="items_count",
                        label="At least one item",
                        group_id="objects",
                        field_paths=["items"],
                        required_for_statuses=["received"],
                        severity="blocking",
                        help_text="Add at least one item to this entry.",
                        has_predicate=True,
                    ),
                    ProcedureRequirement(
                        id="entry_location",
                        label="Storage location",
                        group_id="objects",
                        field_paths=["items"],
                        required_for_statuses=["processed"],
                        severity="recommended",
                        help_text="Each item should have a storage location assigned.",
                        has_predicate=True,
                    ),
                    ProcedureRequirement(
                        id="entry_image",
                        label="Object image",
                        group_id="objects",
                        field_paths=["media_count"],
                        required_for_statuses=[],
                        severity="recommended",
                        help_text="Photograph documenting the object at time of entry.",
                        has_predicate=True,
                    ),
                ],
            ),
            ProcedureRequirementGroup(
                id="duration",
                label="Duration & Return",
                section_id="duration",
                requirements=[
                    ProcedureRequirement(
                        id="expected_duration",
                        label="Expected duration",
                        group_id="duration",
                        field_paths=["expected_duration"],
                        required_for_statuses=[],
                        severity="recommended",
                        help_text="How long you expect to keep the objects.",
                    ),
                    ProcedureRequirement(
                        id="expected_return_date",
                        label="Expected return date",
                        group_id="duration",
                        field_paths=["expected_return_date"],
                        required_for_statuses=[],
                        severity="recommended",
                        help_text="When the objects should be returned to the depositor.",
                    ),
                    ProcedureRequirement(
                        id="conditions",
                        label="Conditions",
                        group_id="duration",
                        field_paths=["conditions"],
                        required_for_statuses=[],
                        severity="info",
                        help_text="Any special conditions for the temporary custody.",
                    ),
                ],
            ),
            ProcedureRequirementGroup(
                id="insurance",
                label="Insurance",
                section_id="insurance",
                requirements=[
                    ProcedureRequirement(
                        id="insurance_value",
                        label="Insurance value",
                        group_id="insurance",
                        field_paths=["insurance_value"],
                        required_for_statuses=["processed"],
                        severity="recommended",
                        help_text="The agreed value for insurance purposes.",
                        has_predicate=True,
                    ),
                    ProcedureRequirement(
                        id="insurance_currency",
                        label="Insurance currency",
                        group_id="insurance",
                        field_paths=["insurance_currency"],
                        required_for_statuses=[],
                        severity="info",
                        help_text="Currency for the insurance value.",
                    ),
                    ProcedureRequirement(
                        id="insurance_note",
                        label="Insurance notes",
                        group_id="insurance",
                        field_paths=["insurance_note"],
                        required_for_statuses=[],
                        severity="info",
                        help_text="Additional insurance arrangements or notes.",
                    ),
                ],
            ),
            ProcedureRequirementGroup(
                id="terms-acceptance",
                label="Terms & Conditions",
                section_id="terms-acceptance",
                requirements=[
                    ProcedureRequirement(
                        id="terms_accepted",
                        label="Terms accepted",
                        group_id="terms-acceptance",
                        field_paths=["terms_accepted"],
                        required_for_statuses=["processed", "returned"],
                        severity="blocking",
                        help_text="Documented acceptance of terms is required before objects enter your care. This blocks transition to Processed and Returned statuses.",
                        has_predicate=True,
                    ),
                    ProcedureRequirement(
                        id="terms_accepted_date",
                        label="Acceptance date",
                        group_id="terms-acceptance",
                        field_paths=["terms_accepted_date"],
                        required_for_statuses=["processed"],
                        severity="recommended",
                        help_text="When the depositor accepted the terms.",
                        has_predicate=True,
                    ),
                    ProcedureRequirement(
                        id="terms_accepted_by",
                        label="Accepted by",
                        group_id="terms-acceptance",
                        field_paths=["terms_accepted_by"],
                        required_for_statuses=["processed"],
                        severity="recommended",
                        help_text="Name of the person who accepted the terms.",
                        has_predicate=True,
                    ),
                    ProcedureRequirement(
                        id="acceptance_method",
                        label="Acceptance method",
                        group_id="terms-acceptance",
                        field_paths=["acceptance_method"],
                        required_for_statuses=[],
                        severity="info",
                        help_text="How acceptance was documented (signature, email, verbal).",
                    ),
                    ProcedureRequirement(
                        id="signature_reference",
                        label="Signature reference",
                        group_id="terms-acceptance",
                        field_paths=["signature_reference"],
                        required_for_statuses=[],
                        severity="info",
                        help_text="Reference to the signed document or signature image.",
                    ),
                ],
            ),
            ProcedureRequirementGroup(
                id="receipt",
                label="Receipt",
                section_id="entry",
                requirements=[
                    ProcedureRequirement(
                        id="receipt_issued",
                        label="Receipt issued to depositor",
                        group_id="receipt",
                        field_paths=["receipt_reference"],
                        required_for_statuses=["processed"],
                        severity="recommended",
                        help_text="The depositor must be given a copy of the entry record.",
                    ),
                    ProcedureRequirement(
                        id="signed_entry_form",
                        label="Signed entry form",
                        group_id="receipt",
                        field_paths=["signed_document_types"],
                        required_for_statuses=["processed"],
                        severity="recommended",
                        help_text="Object Entry requires a signature from the owner/depositor on the entry form.",
                        has_predicate=True,
                    ),
                ],
            ),
        ],
    )
)
