/**
 * Shared plumbing for the route and modal sweeps.
 *
 * Both walk every route the application declares, so both need the same three
 * things: the route list, a signed-in page, and real ids to substitute. Kept here
 * rather than copied into each spec, because the copy is what drifts.
 *
 * Distinct from route-generator.ts, which derives routes from navigationConfig —
 * that is the navigation, and covers what a user can click to. This reads the
 * route table itself, which also includes detail, edit and create routes that no
 * nav item points at.
 */
import { existsSync, readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

import type { Page } from '@playwright/test';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROUTE_CONFIG = join(HERE, '../../../src/app/routeConfig.tsx');
// tests/.auth/, two levels up from tests/e2e/utils/.
const ROUTE_IDS = join(HERE, '../../.auth/route-ids.json');

/** Absolute route paths declared in the app's route config. */
export function declaredRoutes(): string[] {
  const source = readFileSync(ROUTE_CONFIG, 'utf8');
  const found = new Set<string>();
  for (const match of source.matchAll(/<Route\s+path="([^"]+)"/g)) {
    const path = match[1];
    // Relative children need their parent resolved; absolute paths are the
    // overwhelming majority. Splat routes are containers, not pages.
    if (path.startsWith('/') && !path.includes('*')) found.add(path);
  }
  return [...found].sort();
}

/**
 * Ids for route parameters, generated by backend/scripts/dump_route_ids.py.
 * Absent is fine: routes needing an id are then skipped and counted.
 */
export function loadRouteIds(): Record<string, string> {
  if (!existsSync(ROUTE_IDS)) return {};
  try {
    return JSON.parse(readFileSync(ROUTE_IDS, 'utf8'));
  } catch {
    return {};
  }
}

/**
 * Sign in through the real login route.
 *
 * Not the setup project: /api/test-support/mint-session is disabled outside
 * development, and a stack running as production is exactly the shape worth
 * sweeping. Its own env vars, because PLAYWRIGHT_TEST_EMAIL names a user for the
 * passwordless mint-session flow and reusing it here means a 401.
 */
export async function signIn(page: Page): Promise<{ orgId: string; orgSlug?: string }> {
  const email = process.env.SWEEP_EMAIL || 'e2e-test@example.com';
  const password = process.env.SWEEP_PASSWORD || 'E2E-Test-Password-123!';

  const csrf = await page.request.get('/api/auth/csrf');
  const csrfToken = csrf.ok() ? (await csrf.json()).csrf_token : undefined;
  const login = await page.request.post('/api/auth/login', {
    data: { email, password },
    headers: csrfToken
      ? { 'Content-Type': 'application/json', 'X-CSRF-Token': csrfToken }
      : { 'Content-Type': 'application/json' },
  });
  if (!login.ok()) {
    throw new Error(`login failed for ${email}: ${login.status()}`);
  }

  const me = await page.request.get('/api/me');
  if (!me.ok()) throw new Error('could not identify the signed-in user');
  const body = await me.json();
  const orgId: string | undefined =
    body.active_organization_id ??
    body.organization_id ??
    body.organizations?.[0]?.organization_id;
  if (!orgId) throw new Error('/api/me returned no organization');

  // GET /api/organizations/{id} answers 405, so the slug comes from the id map.
  return { orgId, orgSlug: loadRouteIds().orgSlug };
}

/** A visitable URL, or null when a parameter has no value available. */
export function buildUrl(
  route: string,
  orgId: string,
  ids: Record<string, string>,
  orgSlug?: string,
): string | null {
  let url = route.replace(/:orgId/g, orgId);
  const slug = orgSlug ?? ids.orgSlug;
  if (slug) url = url.replace(/:orgSlug/g, slug);
  url = url.replace(/:([A-Za-z]+)/g, (whole, name: string) => ids[name] ?? whole);
  return url.includes(':') ? null : url;
}
