import type { CollectionObject } from '../../../lib/schemas';

/**
 * Realistic fixture for a fully-populated CollectionObject record.
 * Used across CollectionObjectWorkspacePage tests.
 */
export function makeCollectionObject(
  overrides: Partial<CollectionObject> = {},
): CollectionObject {
  const base = {
    object_id: 'obj-123',
    organization_id: 'org-1',
    object_number: '2024.001',
    object_name: 'Vase',
    object_type: 'ceramic',
    object_status: 'accessioned',
    is_discoverable: false,
    titles: [{ title: 'Blue and White Vase', is_primary: true } as never],
    classifications: [
      { term: 'ceramic', value_key: 'ceramic' } as never,
    ],
    brief_description: 'A small blue and white porcelain vase from the Ming dynasty.',
    full_description: null,
    comments: null,
    distinguishing_features: null,
    content_description: null,
    creation_date_display: 'c. 1500',
    creation_date_earliest: null,
    creation_date_latest: null,
    creation_place: 'Jingdezhen, China',
    production_reason: null,
    production_note: null,
    physical_description: null,
    color: 'blue and white',
    form: null,
    materials: null,
    techniques: null,
    material_count: 2,
    technique_count: 1,
    measurements: [
      { dimension: 'height', value: 25, unit: 'cm', part: null },
    ] as never,
    inscriptions: null,
    edition: null,
    copy_number: null,
    edition_note: null,
    state_number: null,
    total_states: null,
    state_description: null,
    catalog_level: null,
    age: null,
    age_qualifier: null,
    age_unit: null,
    orientation: null,
    arrangement: null,
    installation_instructions: null,
    technical_attributes: null,
    facture_description: null,
    watermarks: null,
    components: null,
    condition_rating: null,
    condition_date: null,
    condition_note: 'Stable, minor crazing on glaze.',
    completeness: 'complete',
    completeness_note: null,
    conservation_priority: null,
    next_condition_check_date: null,
    hazards: null,
    environmental_requirements: null,
    salvage_priority: null,
    handling_requirements: null,
    subjects: [],
    associated_people: null,
    associated_places: null,
    provenance: 'Acquired from Smith Estate in 2020.',
    provenance_structured: null,
    exhibition_history: null,
    publication_history: null,
    object_history_note: null,
    usage: null,
    usage_note: null,
    associated_events: null,
    associated_organizations: null,
    associated_concepts: null,
    associated_cultural_affinity: null,
    association_note: null,
    excavation_site: null,
    excavation_date: null,
    archaeological_context: null,
    field_collection_number: null,
    depicted_people: null,
    depicted_organizations: null,
    depicted_places: null,
    depicted_events: null,
    depicted_objects: null,
    depicted_activities: null,
    depicted_concepts: null,
    acquisition_date: '2020-06-15',
    acquisition_method: 'gift',
    acquisition_source: 'Smith Estate',
    acquisition_source_type: null,
    acquisition_cost: null,
    acquisition_currency: null,
    acquisition_funding_source: null,
    acquisition_provisos: null,
    acquisition_reason: null,
    acquisition_note: null,
    credit_line: 'Gift of the Smith Family',
    accession_date: '2020-07-01',
    current_value: null,
    current_value_currency: null,
    current_value_date: null,
    insurance_value: null,
    insurance_value_currency: null,
    insurance_note: null,
    valuation_history: null,
    barcode: null,
    last_inventoried_date: null,
    last_inventoried_by: null,
    current_location_id: 'loc-1',
    current_location_fitness: null,
    current_location_note: null,
    current_location_date: null,
    current_location: {
      location_id: 'loc-1',
      name: 'Gallery A',
      path: 'Main Building / Floor 2 / Gallery A',
      location_type: 'gallery',
      on_display: true,
    },
    home_location_id: null,
    home_location: null,
    custom_fields: null,
    constituents: [],
    creators: [],
    contacts: null,
    person_authorities: [],
    place_authorities: [],
    style_periods: [],
    related_objects: [],
    citations: [],
    parts: [],
    parts_count: 0,
    relationship_count: 0,
    citation_count: 0,
    event_count: 0,
    primary_image_url: 'https://example.com/img/obj-123.jpg',
    other_numbers: [],
    department_id: null,
    number_of_objects: 1,
    category: null,
    is_on_display: true,
    discoverable_at: null,
    other_numbers_v2: null,
    acquisition: null,
    created_at: '2020-07-01T00:00:00Z',
    updated_at: '2024-01-15T12:00:00Z',
    created_by: 'user-1',
    updated_by: 'user-1',
    ...overrides,
  } as unknown as CollectionObject;
  return base;
}

export const mockEmptyObject = (): CollectionObject =>
  makeCollectionObject({
    titles: [],
    classifications: [],
    brief_description: null,
    full_description: null,
    comments: null,
    distinguishing_features: null,
    content_description: null,
    creation_date_display: null,
    creation_place: null,
    measurements: [],
    material_count: 0,
    technique_count: 0,
    inscriptions: null,
    physical_description: null,
    color: null,
    form: null,
    edition: null,
    state_number: null,
    condition_note: null,
    completeness: null,
    handling_requirements: null,
    current_location_id: null,
    home_location_id: null,
    current_location: null,
    acquisition: null,
    acquisition_method: null,
    acquisition_date: null,
    acquisition_source: null,
    credit_line: null,
    provenance: null,
    object_history_note: null,
    usage: null,
    excavation_site: null,
    primary_image_url: null,
  } as Partial<CollectionObject>);
