import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import { MemoryRouter, Routes, Route } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import CategoriesPage from '../../pages/content/CategoriesPage';
import * as contentApi from '../../lib/api/content';

vi.mock('../../lib/api/content', () => ({
  listCategories: vi.fn(),
  createCategory: vi.fn(),
  updateCategory: vi.fn(),
  deleteCategory: vi.fn(),
}));

const mockListCategories = vi.mocked(contentApi.listCategories);
const mockCreateCategory = vi.mocked(contentApi.createCategory);

function renderPage(orgId = 'org-1') {
  const qc = new QueryClient({
    defaultOptions: { queries: { retry: false }, mutations: { retry: false } },
  });
  return render(
    <QueryClientProvider client={qc}>
      <MemoryRouter initialEntries={[`/organizations/${orgId}/content/categories`]}>
        <Routes>
          <Route
            path="/organizations/:orgId/content/categories"
            element={<CategoriesPage />}
          />
        </Routes>
      </MemoryRouter>
    </QueryClientProvider>
  );
}

describe('CategoriesPage', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders header and add button', async () => {
    mockListCategories.mockResolvedValue({ data: [] } as never);
    renderPage();
    expect(screen.getByRole('heading', { name: 'Categories' })).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /add category/i })).toBeInTheDocument();
  });

  it('renders empty state when no categories', async () => {
    mockListCategories.mockResolvedValue({ data: [] } as never);
    renderPage();
    await waitFor(() => {
      expect(screen.getByText('No categories yet')).toBeInTheDocument();
    });
  });

  it('renders a category row', async () => {
    mockListCategories.mockResolvedValue({
      data: [
        {
          category_id: 'c-1',
          name: 'Exhibitions',
          slug: 'exhibitions',
          description: 'All exhibition posts',
          sort_order: 0,
        },
      ],
    } as never);
    renderPage();

    await waitFor(() => {
      expect(screen.getByText('Exhibitions')).toBeInTheDocument();
    });
    expect(screen.getByText('/exhibitions')).toBeInTheDocument();
    expect(screen.getByText('All exhibition posts')).toBeInTheDocument();
  });

  it('opens the create modal with autogenerated slug', async () => {
    mockListCategories.mockResolvedValue({ data: [] } as never);
    renderPage();

    const addBtns = screen.getAllByRole('button', { name: /add category/i });
    fireEvent.click(addBtns[0]);

    expect(screen.getByRole('heading', { name: 'Add Category' })).toBeInTheDocument();

    const nameInput = screen.getByLabelText('Name');
    fireEvent.change(nameInput, { target: { value: 'Acquisitions News' } });

    const slugInput = screen.getByLabelText('Slug') as HTMLInputElement;
    expect(slugInput.value).toBe('acquisitions-news');
  });

  it('disables create button when name is empty', async () => {
    mockListCategories.mockResolvedValue({ data: [] } as never);
    renderPage();

    const addBtns = screen.getAllByRole('button', { name: /add category/i });
    fireEvent.click(addBtns[0]);

    const create = screen.getByRole('button', { name: /^create$/i });
    expect(create).toBeDisabled();
  });

  it('calls createCategory on submit', async () => {
    mockListCategories.mockResolvedValue({ data: [] } as never);
    mockCreateCategory.mockResolvedValue({ data: { category_id: 'new' } } as never);
    renderPage();

    fireEvent.click(screen.getAllByRole('button', { name: /add category/i })[0]);

    fireEvent.change(screen.getByLabelText('Name'), {
      target: { value: 'News' },
    });

    fireEvent.click(screen.getByRole('button', { name: /^create$/i }));

    await waitFor(() => {
      expect(mockCreateCategory).toHaveBeenCalled();
    });
  });
});
