// Re-export everything from polygonUtils
// Using direct re-export for verbatimModuleSyntax compatibility
import {
  type Vertex,
  type WallOpening,
  type Wall,
  type Column,
  type BackgroundImage,
  type PolygonGeometry,
  type RectangularGeometry,
  type FloorPlanGeometry,
  isRectangular,
  isPolygon,
  rectangularToPolygon,
  normalizeGeometry,
  calculateWallLength,
  calculateWallAngle,
  calculateWallMidpoint,
  calculateWallNormal,
  calculatePolygonCentroid,
  calculatePolygonArea,
  calculateBoundingBox,
  isPointInPolygon,
  floorPlanTo3D,
  threeDToFloorPlan,
  calculateArtworkPosition,
  generateId,
  snapToGrid,
  snapToAngle,
  distance,
  closestPointOnSegment,
} from './polygonUtils';

export {
  type Vertex,
  type WallOpening,
  type Wall,
  type Column,
  type BackgroundImage,
  type PolygonGeometry,
  type RectangularGeometry,
  type FloorPlanGeometry,
  isRectangular,
  isPolygon,
  rectangularToPolygon,
  normalizeGeometry,
  calculateWallLength,
  calculateWallAngle,
  calculateWallMidpoint,
  calculateWallNormal,
  calculatePolygonCentroid,
  calculatePolygonArea,
  calculateBoundingBox,
  isPointInPolygon,
  floorPlanTo3D,
  threeDToFloorPlan,
  calculateArtworkPosition,
  generateId,
  snapToGrid,
  snapToAngle,
  distance,
  closestPointOnSegment,
};
