"""timestamptz for preservation and guide_metrics

Revision ID: 9389aa1e97c3
Revises: 32a96cbe0ba8
Create Date: 2026-09-04 15:01:44.498634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9389aa1e97c3'
down_revision: Union[str, Sequence[str], None] = '32a96cbe0ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Migration runs as the DB owner/migrator role (BYPASSRLS).
# Connection URL comes from ALEMBIC_DATABASE_URL (not DATABASE_URL).
#
# IMPORTANT - Data migrations that INSERT/UPDATE/DELETE rows in org-scoped
# tables must set organization_id explicitly on every row.  Do NOT rely on
# SET LOCAL row_security = off (legacy pattern, do not copy).
#
# If your migration touches org-scoped data, add this marker comment so the
# lint check (make lint-migrations) passes:
#   # MADRONA_MIGRATION_STRATEGY: owner
# ---------------------------------------------------------------------------


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guide_metrics', 'request_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="request_started_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('information_packages', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('preservation_action_plans', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="scheduled_for AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('preservation_action_plans', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('preservation_action_plans', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('preservation_policies', 'approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="approved_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('replication_records', 'last_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_verified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('replication_records', 'last_verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_verified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('preservation_policies', 'approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="approved_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('preservation_action_plans', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('preservation_action_plans', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('preservation_action_plans', 'scheduled_for',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_for AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('information_packages', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('guide_metrics', 'request_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="request_started_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    # ### end Alembic commands ###
