"""add model version pinning to agent plans + steps

Revision ID: b7c8d9e0f1a2
Revises: 03ad46fdde10
Create Date: 2026-05-17 10:00:00.000000

Guide Studio v1 §7.4 (model version pinning in the plan audit trail).

Adds nullable `model_provider`, `model_id`, `model_version` to
`agent_plans` (the planner LLM call that produced the plan) and
`agent_plan_steps` (steps that produce LLM/tool calls). Nullable is
correct, not a defaulted backfill: a NULL means "no model recorded for
this row" and pre-existing rows genuinely have no captured model
identity. Back-filling a guessed model would defeat the forensic point
of §7.4 — six months from now an auditor must be able to trust that a
recorded model_id is the model that actually ran, not an inferred one.

Hand-written (not autogenerated) following the 03ad46fdde10 precedent:
the autogen run pulls in ~600 lines of pre-existing unrelated
TIMESTAMP/index drift that must not be bundled with a feature change.
Idempotent ADD ... IF NOT EXISTS so a re-run, a partially-applied
state, or a Base.metadata.create_all test bootstrap doesn't hard-fail.
"""
from typing import Sequence, Union

from alembic import op


revision: str = 'b7c8d9e0f1a2'
down_revision: Union[str, Sequence[str], None] = '03ad46fdde10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_TABLES = ("agent_plans", "agent_plan_steps")
_COLUMNS = (
    ("model_provider", "Provider that served the LLM call (ollama|runpod|claude)."),
    ("model_id", "Model identifier as configured at call time (e.g. claude-opus-4-7, qwen2.5:14b)."),
    ("model_version", "Concrete version when the provider reports one distinct from model_id; NULL otherwise."),
)


def upgrade() -> None:
    for table in _TABLES:
        for column, comment in _COLUMNS:
            op.execute(
                f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} TEXT"
            )
            op.execute(
                f"COMMENT ON COLUMN {table}.{column} IS '{comment}'"
            )


def downgrade() -> None:
    for table in _TABLES:
        for column, _ in _COLUMNS:
            op.execute(
                f"ALTER TABLE {table} DROP COLUMN IF EXISTS {column}"
            )
