"""timestamptz for all naive timestamp columns

Revision ID: 40bc2f6affce
Revises: b8d4f1e6a920
Create Date: 2026-09-04 14:58:30.677686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40bc2f6affce'
down_revision: Union[str, Sequence[str], None] = 'b8d4f1e6a920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Migration runs as the DB owner/migrator role (BYPASSRLS).
# Connection URL comes from ALEMBIC_DATABASE_URL (not DATABASE_URL).
#
# IMPORTANT - Data migrations that INSERT/UPDATE/DELETE rows in org-scoped
# tables must set organization_id explicitly on every row.  Do NOT rely on
# SET LOCAL row_security = off (legacy pattern, do not copy).
#
# If your migration touches org-scoped data, add this marker comment so the
# lint check (make lint-migrations) passes:
#   # MADRONA_MIGRATION_STRATEGY: owner
# ---------------------------------------------------------------------------


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_drafts', 'decided_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="decided_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_drafts', 'applied_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="applied_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_plan_steps', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_plan_steps', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_plans', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_plans', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('api_keys', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('approval_requests', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="reviewed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('email_verification_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('email_verification_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mfa_recovery_codes', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mfa_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mfa_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="read_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('org_provisioning_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('org_provisioning_jobs', 'welcome_email_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="welcome_email_sent_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('org_provisioning_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('org_provisioning_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_role_labels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_role_labels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('organization_applications', 'contract_start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="contract_start_date AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('organization_applications', 'contract_end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="contract_end_date AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('organization_invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('organization_invitations', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('organization_invitations', 'last_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_sent_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('organization_storage_configs', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="verified_at AT TIME ZONE 'UTC'",
               existing_comment='Timestamp of last successful connection test',
               existing_nullable=True)
    op.alter_column('organization_storage_configs', 'migration_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="migration_started_at AT TIME ZONE 'UTC'",
               existing_comment='Timestamp when migration was started',
               existing_nullable=True)
    op.alter_column('organizations', 'storage_metered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="storage_metered_at AT TIME ZONE 'UTC'",
               existing_comment='Timestamp of last storage metering run',
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="revoked_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'mfa_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="mfa_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('sla_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="email_verified_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'google_token_expiry',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="google_token_expiry AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'recovery_codes_generated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="recovery_codes_generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('visitors', 'email_consent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="email_consent_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('visits', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="ended_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('visits', 'recap_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="recap_sent_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('barcode_labels', 'last_printed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_printed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('collection_objects', 'current_location_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="current_location_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('collection_objects', 'discoverable_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="discoverable_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('collection_objects', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('constituent_xrefs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('constituents', 'ulan_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="ulan_synced_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('constituents', 'ulan_modified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="ulan_modified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('constituents', 'verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="verified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('events', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="start_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('events', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="end_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('exhibition_labels', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="reviewed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('exhibition_labels', 'approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="approved_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('exhibition_labels', 'last_printed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_printed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('exhibition_loans', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_synced_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('expiration_alerts', 'dismissed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="dismissed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('expiration_alerts', 'email_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="email_sent_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('incident_reports', 'incident_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="incident_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('incident_reports', 'discovered_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="discovered_date AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='collections')
    op.alter_column('movements', 'movement_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="movement_date AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='collections')
    op.alter_column('object_parts', 'current_location_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="current_location_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('other_number_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='collections')
    op.alter_column('publish_schedules', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="scheduled_for AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='collections')
    op.alter_column('publish_schedules', 'executed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="executed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('vocabulary_mappings', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="reviewed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('vocabulary_terms', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('vocabulary_terms', 'getty_modified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="getty_modified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('vocabulary_terms', 'hierarchy_fetched_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="hierarchy_fetched_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('workspaces', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('pages', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="published_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='content')
    op.alter_column('pages', 'publish_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="publish_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='content')
    op.alter_column('dataset_transformers', 'activated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="activated_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('entity_current', 'extracted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="extracted_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='flow')
    op.alter_column('entity_current', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_seen_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='flow')
    op.alter_column('entity_current', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('entity_fields', 'modified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="modified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('jobs', 'scheduled_for',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="scheduled_for AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('jobs', 'locked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="locked_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('jobs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('run_destination_steps', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('run_destination_steps', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('run_source_steps', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('run_source_steps', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="published_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'error_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="error_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'rolled_back_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="rolled_back_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('collection_feedback_requests', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'ai_descriptions_generated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="ai_descriptions_generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="published_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'metadata_reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="metadata_reviewed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'last_fixity_check',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_fixity_check AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'inherited_metadata_updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="inherited_metadata_updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'ai_processed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="ai_processed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_collections', 'public_share_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="public_share_expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_collections', 'consent_cleared_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="consent_cleared_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_collections', 'last_refreshed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_refreshed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_request_items', 'downloaded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="downloaded_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_requests', 'review_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="review_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_requests', 'approval_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="approval_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_requests', 'fulfilled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="fulfilled_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_requests', 'download_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="download_expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_locks', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='media')
    op.alter_column('media_processing_jobs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_processing_jobs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_search_subscriptions', 'last_checked_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="last_checked_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('workspace_action_runs', 'artifact_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="artifact_expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('workspace_action_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('workspace_action_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('report_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='reports')
    op.alter_column('report_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='reports')
    op.alter_column('report_runs', 'dismissed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               postgresql_using="dismissed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='reports')
    # reports.report_schedules was altered here too. The table is gone with the
    # reports module, and the consolidated migration builds from
    # Base.metadata.create_all, so a database created after that removal never
    # has it — these statements would fail on a fresh migrate. Databases that
    # already ran this revision keep the column types they were given.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_runs', 'dismissed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="dismissed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='reports')
    op.alter_column('report_runs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='reports')
    op.alter_column('report_runs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='reports')
    op.alter_column('workspace_action_runs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('workspace_action_runs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('workspace_action_runs', 'artifact_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="artifact_expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_search_subscriptions', 'last_checked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_checked_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_processing_jobs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_processing_jobs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_locks', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='media')
    op.alter_column('media_download_requests', 'download_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="download_expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_requests', 'fulfilled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="fulfilled_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_requests', 'approval_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="approval_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_requests', 'review_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="review_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_download_request_items', 'downloaded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="downloaded_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_collections', 'last_refreshed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_refreshed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_collections', 'consent_cleared_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="consent_cleared_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media_collections', 'public_share_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="public_share_expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'ai_processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="ai_processed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'inherited_metadata_updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="inherited_metadata_updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'last_fixity_check',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_fixity_check AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'metadata_reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="metadata_reviewed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="published_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('media', 'ai_descriptions_generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="ai_descriptions_generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('collection_feedback_requests', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='media')
    op.alter_column('runs', 'rolled_back_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="rolled_back_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'error_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="error_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="published_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('runs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('run_source_steps', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('run_source_steps', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('run_destination_steps', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('run_destination_steps', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('jobs', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="finished_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('jobs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('jobs', 'locked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="locked_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('jobs', 'scheduled_for',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_for AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('entity_fields', 'modified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="modified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('entity_current', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('entity_current', 'last_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_seen_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='flow')
    op.alter_column('entity_current', 'extracted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="extracted_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='flow')
    op.alter_column('dataset_transformers', 'activated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="activated_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='flow')
    op.alter_column('pages', 'publish_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="publish_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='content')
    op.alter_column('pages', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="published_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='content')
    op.alter_column('workspaces', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('vocabulary_terms', 'hierarchy_fetched_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="hierarchy_fetched_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('vocabulary_terms', 'getty_modified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="getty_modified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('vocabulary_terms', 'last_used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('vocabulary_mappings', 'reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="reviewed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('publish_schedules', 'executed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="executed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('publish_schedules', 'scheduled_for',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="scheduled_for AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='collections')
    op.alter_column('other_number_types', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='collections')
    op.alter_column('object_parts', 'current_location_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="current_location_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('movements', 'movement_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="movement_date AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='collections')
    op.alter_column('incident_reports', 'discovered_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="discovered_date AT TIME ZONE 'UTC'",
               existing_nullable=False,
               schema='collections')
    op.alter_column('incident_reports', 'incident_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="incident_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('expiration_alerts', 'email_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="email_sent_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('expiration_alerts', 'dismissed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="dismissed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('exhibition_loans', 'last_synced_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_synced_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('exhibition_labels', 'last_printed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_printed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('exhibition_labels', 'approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="approved_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('exhibition_labels', 'reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="reviewed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('events', 'end_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="end_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('events', 'start_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="start_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('constituents', 'verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="verified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('constituents', 'ulan_modified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="ulan_modified_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('constituents', 'ulan_synced_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="ulan_synced_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('constituent_xrefs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('collection_objects', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="deleted_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('collection_objects', 'discoverable_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="discoverable_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('collection_objects', 'current_location_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="current_location_date AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('barcode_labels', 'last_printed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_printed_at AT TIME ZONE 'UTC'",
               existing_nullable=True,
               schema='collections')
    op.alter_column('visits', 'recap_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="recap_sent_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('visits', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="ended_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('visitors', 'email_consent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="email_consent_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'recovery_codes_generated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="recovery_codes_generated_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'google_token_expiry',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="google_token_expiry AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('users', 'email_verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="email_verified_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('sla_policies', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('refresh_tokens', 'mfa_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="mfa_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'revoked_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="revoked_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('password_reset_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('organizations', 'storage_metered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="storage_metered_at AT TIME ZONE 'UTC'",
               existing_comment='Timestamp of last storage metering run',
               existing_nullable=True)
    op.alter_column('organization_storage_configs', 'migration_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="migration_started_at AT TIME ZONE 'UTC'",
               existing_comment='Timestamp when migration was started',
               existing_nullable=True)
    op.alter_column('organization_storage_configs', 'verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="verified_at AT TIME ZONE 'UTC'",
               existing_comment='Timestamp of last successful connection test',
               existing_nullable=True)
    op.alter_column('organization_invitations', 'last_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_sent_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('organization_invitations', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('organization_invitations', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('organization_applications', 'contract_end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="contract_end_date AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('organization_applications', 'contract_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="contract_start_date AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('org_role_labels', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="updated_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_role_labels', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_provisioning_jobs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="created_at AT TIME ZONE 'UTC'",
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_provisioning_jobs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('org_provisioning_jobs', 'welcome_email_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="welcome_email_sent_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('org_provisioning_jobs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('notifications', 'read_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="read_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mfa_reset_tokens', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('mfa_reset_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('mfa_recovery_codes', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('email_verification_tokens', 'used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('email_verification_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=False)
    op.alter_column('approval_requests', 'reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="reviewed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('api_keys', 'last_used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="last_used_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('api_keys', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="expires_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_plans', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_plans', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_plan_steps', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="completed_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_plan_steps', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="started_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_drafts', 'applied_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="applied_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    op.alter_column('agent_drafts', 'decided_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               postgresql_using="decided_at AT TIME ZONE 'UTC'",
               existing_nullable=True)
    # ### end Alembic commands ###
