/**
 * Flat navigation catalog.
 *
 * Derived from `navigationConfig.ts`, this module flattens the nested product
 * navigation into a searchable list of destinations. Used by:
 *   - the command palette (Cmd+K) for fuzzy jump-to
 *   - the AI Guide's `navigate_to` tool (via `backend/app/services/agent_tools/nav_catalog.json`)
 *
 * The JSON artifact at `backend/app/services/agent_tools/nav_catalog.json` is generated by the vitest
 * snapshot in `src/test/lib/navigationCatalog.test.ts` and consumed by the
 * Python backend. Run `pnpm run build:nav-catalog` to regenerate after editing
 * `navigationConfig.ts`.
 */

import {
  products,
  adminItems,
  platformAdminItems,
  type NavItem,
} from './navigationConfig';

/** One searchable destination. Icons are intentionally omitted. */
export interface NavEntry {
  /** Stable identifier, e.g. `collections:conservation`. */
  id: string;
  /** Product or scope: `collections`, `media`, `bridge`, `admin`, etc. */
  product: string;
  /** Human label shown in UI results. */
  label: string;
  /** Path pattern with `:orgId` placeholder — substitute at render time. */
  pathPattern: string;
  /** Full breadcrumb from product root to this item. */
  breadcrumb: string[];
  /** Lowercased search tokens: label words, breadcrumbs, synonyms. */
  keywords: string[];
  /** RBAC permission required to see/use this destination. */
  permission?: string;
  /** App subscription key required to see this destination. */
  appKey?: string;
  /** Optional extended description for model/tool grounding. */
  description?: string;
}

/**
 * Per-item synonyms to help fuzzy + model matching when a user's
 * phrasing doesn't contain the exact label. Keyed by nav item id.
 */
const SYNONYMS: Record<string, string[]> = {
  // Bridge
  pipeline: ['bridge', 'data pipeline', 'etl'],
  runs: ['run history', 'job history', 'executions'],
  datasets: ['source data', 'raw data'],

  // Collections — work
  'my-tasks': ['tasks', 'todo', 'inbox', 'assignments'],
  workspaces: ['work sets', 'batch work'],
  approvals: ['pending approvals', 'review queue'],

  // Collections — core
  objects: [
    'catalog',
    'cataloging',
    'collection objects',
    'records',
    // Both spellings on purpose: the sector is split, and this list is
    // search synonyms, not prose.
    'artefacts',
    'artifacts',
    'items',
  ],

  // Transactions
  entries: ['object entry', 'incoming', 'receipt', 'intake'],
  acquisitions: ['accession', 'accessioning', 'donation', 'purchase', 'acquire'],
  'loans-in': ['incoming loan', 'borrow', 'inbound loan', 'loan in'],
  'loans-out': ['outgoing loan', 'lending', 'outbound loan', 'loan out'],
  exits: ['departures', 'object exit', 'outgoing'],
  deaccessions: ['deaccession', 'disposal', 'removal from collection'],
  movements: ['object movement', 'relocate', 'move object'],
  shipments: ['shipping', 'transport', 'freight'],

  // Exhibitions
  'exhibitions-list': ['exhibition', 'show', 'display', 'gallery'],
  venues: ['locations', 'exhibition venues', 'buildings'],

  // Care & risk
  'risk-overview': ['risks', 'risk assessment', 'hazards'],
  'condition-reports': ['condition', 'condition check', 'assessment'],
  conservation: ['treatment', 'restoration', 'repair', 'conservation treatment'],
  incidents: ['incident report', 'damage report', 'loss'],
  valuations: ['appraisal', 'value', 'worth', 'valuation'],
  insurance: ['policy', 'insurance policy', 'coverage'],
  indemnity: ['indemnification', 'government indemnity'],
  'emergency-plans': ['emergency', 'disaster plan', 'salvage plan'],

  // Rights & reproduction
  rights: ['ip', 'copyright', 'intellectual property', 'permissions'],
  'use-requests': ['use request', 'permission request'],
  'reproduction-requests': ['repro', 'reproduction', 'image request'],

  // People & programs
  constituents: ['people', 'persons', 'organizations', 'contacts', 'donors', 'artists'],
  events: ['programs', 'calendar'],
  vocabularies: ['controlled vocabularies', 'thesaurus', 'authorities', 'terms'],

  // Governance
  reviews: ['collections review', 'review'],
  audits: ['audit', 'inventory audit', 'audit campaigns'],

  // Inventory
  'barcode-labels': ['labels', 'print labels', 'barcodes'],
  'barcode-scanner': ['scanner', 'scan', 'barcode scanner'],
  'scan-history': ['scans', 'scan log'],

  // Media
  library: ['media library', 'dam', 'assets', 'images', 'photos'],
  collections: ['lightbox', 'lightboxes', 'media collections'],
  'download-requests': ['downloads', 'download queue'],
  publishing: ['publish media', 'publication'],

  // Content
  pages: ['web pages', 'site pages'],
  posts: ['blog', 'articles', 'news'],

  // Guide
  'guide-chat': ['chat playground', 'ask guide', 'assistant playground'],
  'guide-documents': ['guide docs', 'reference documents', 'knowledge base'],

  // Admin
  users: ['members', 'user management', 'team'],
  roles: ['role management', 'permissions', 'rbac'],
  departments: ['org units', 'teams'],
  'entity-audit': ['change history', 'audit log', 'history'],
  'api-keys': ['api tokens', 'api key'],
};

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
}

function buildKeywords(item: NavItem, breadcrumb: string[]): string[] {
  const set = new Set<string>();
  // Full phrases
  set.add(item.label.toLowerCase());
  for (const crumb of breadcrumb) set.add(crumb.toLowerCase());
  // Individual tokens
  for (const token of tokenize(item.label)) set.add(token);
  for (const crumb of breadcrumb) {
    for (const token of tokenize(crumb)) set.add(token);
  }
  // Hand-curated synonyms
  const syns = SYNONYMS[item.id] ?? [];
  for (const syn of syns) set.add(syn.toLowerCase());
  return Array.from(set).sort();
}

function flattenItems(
  items: NavItem[],
  productId: string,
  productLabel: string,
  appKey: string | undefined,
  breadcrumb: string[],
): NavEntry[] {
  const entries: NavEntry[] = [];
  for (const item of items) {
    const currentBreadcrumb = [...breadcrumb, item.label];
    if (item.path) {
      entries.push({
        id: `${productId}:${item.id}`,
        product: productId,
        label: item.label,
        pathPattern: item.path,
        breadcrumb: currentBreadcrumb,
        keywords: buildKeywords(item, [productLabel, ...currentBreadcrumb]),
        permission: item.requiresPermission,
        appKey,
      });
    }
    if (item.children) {
      entries.push(
        ...flattenItems(item.children, productId, productLabel, appKey, currentBreadcrumb),
      );
    }
  }
  return entries;
}

/**
 * Return the full flattened catalog of destinations. Unfiltered — callers
 * should apply `filterByAccess` with the current user's permissions before
 * surfacing entries in UI or passing them to the model.
 */
export function getNavCatalog(): NavEntry[] {
  const entries: NavEntry[] = [];

  for (const product of products) {
    entries.push(
      ...flattenItems(product.items, product.id, product.label, product.appKey, []),
    );
  }

  for (const item of adminItems) {
    entries.push({
      id: `admin:${item.id}`,
      product: 'admin',
      label: item.label,
      pathPattern: item.path,
      breadcrumb: ['Admin', item.label],
      keywords: buildKeywords(
        { id: item.id, label: item.label, icon: item.icon },
        ['Admin', item.label],
      ),
      permission: item.requiresPermission,
    });
  }

  for (const item of platformAdminItems) {
    entries.push({
      id: `platform-admin:${item.id}`,
      product: 'platform-admin',
      label: item.label,
      pathPattern: item.path,
      breadcrumb: ['Platform Admin', item.label],
      keywords: buildKeywords(
        { id: item.id, label: item.label, icon: item.icon },
        ['Platform Admin', item.label],
      ),
      permission: item.requiresPermission,
    });
  }

  // Stable ordering for deterministic snapshot output.
  return entries.sort((a, b) => a.id.localeCompare(b.id));
}

/** Predicate bundle for permission/app-access filtering. */
export interface AccessChecker {
  hasPermission: (permission?: string) => boolean;
  hasAppAccess: (appKey: string) => boolean;
}

/** Drop entries the current user can't access. */
export function filterByAccess(
  entries: NavEntry[],
  checker: AccessChecker,
): NavEntry[] {
  return entries.filter((entry) => {
    if (entry.appKey && !checker.hasAppAccess(entry.appKey)) return false;
    if (entry.permission && !checker.hasPermission(entry.permission)) return false;
    return true;
  });
}

/** Substitute the `:orgId` placeholder with an actual org id. */
export function resolveNavPath(entry: NavEntry, orgId: string): string {
  return entry.pathPattern.replace(':orgId', orgId);
}
